
Fatal error: %s
Stack trace:
#0 [internal function]: gen()
#1 %s(%d): Generator->send(Object(Generator))
#2 {main}
  thrown in %s on line %d