
Fatal error: %s
Stack trace:
#0 %s(%d): foo->{closure}()
#1 {main}
  thrown in %s on line %d