
Fatal error: %s
Stack trace:
#0 %s(%d): foo()
#1 {main}
  thrown in %s on line %d